name:                monad-logger-logstash
version:             0.2.0.1
github:              "mbg/logstash"
license:             MIT
author:              "Michael B. Gale"
maintainer:          "github@michael-gale.co.uk"
copyright:           "Copyright (c) 2021 Michael B. Gale"
license-file:        LICENSE

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Logstash backend for monad-logger.
category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbg/logstash#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- logstash
- monad-logger
- retry
- stm
- stm-chans
- text
- transformers
- unliftio

default-extensions:
- RecordWildCards
- OverloadedStrings

library:
  source-dirs: src

