name: hackage

on:
  push:
    tags:
      - 'logstash-*'
      - 'katip-logstash-*'
      - 'monad-logger-logstash-*'

jobs:
  publish-to-hackage:
    name: 'Publish to Hackage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: 'latest'

      - name: Publish `logstash`
        if: startsWith(github.ref, 'refs/tags/logstash-')
        run: |
          mkdir -p ${{ steps.install-haskell.outputs.stack-root }}
          echo "save-hackage-creds: false" >> ${{ steps.install-haskell.outputs.stack-root }}/config.yaml
          stack upload --pvp-bounds none ./logstash/
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}

      - name: Publish `katip-logstash`
        if: startsWith(github.ref, 'refs/tags/katip-logstash-')
        run: |
          mkdir -p ${{ steps.install-haskell.outputs.stack-root }}
          echo "save-hackage-creds: false" >> ${{ steps.install-haskell.outputs.stack-root }}/config.yaml
          stack upload --pvp-bounds none ./katip-logstash/
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}

      - name: Publish `monad-logger-logstash`
        if: startsWith(github.ref, 'refs/tags/monad-logger-logstash-')
        run: |
          mkdir -p ${{ steps.install-haskell.outputs.stack-root }}
          echo "save-hackage-creds: false" >> ${{ steps.install-haskell.outputs.stack-root }}/config.yaml
          stack upload --pvp-bounds none ./monad-logger-logstash/
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
