name: Build

on:
  push:
    branches: [master]
    tags:
      - 'v*'
    paths:
      - '.github/workflows/**'
      - 'katip-logstash/src/**'
      - 'katip-logstash/package.yaml'
      - 'logstash/src/**'
      - 'logstash/package.yaml'
      - 'monad-logger-logstash/src/**'
      - 'monad-logger-logstash/package.yaml'
      - 'stack*.yaml'
  pull_request:
    branches: [master]
  
jobs:
    build:
      strategy: 
        matrix:
          resolver: 
            - stack
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v1  
      
      - name: Install system dependencies 
        run: |
          sudo apt-get install libpcre3-dev
          
      - name: Install the Haskell Stack 
        run: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}
          restore-keys: |
              ${{ runner.os }}-stack
              ${{ runner.os }}

      - name: Install GHC 
        run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal --install-ghc setup

      - name: Install dependencies
        run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --only-dependencies --fast
          
      - name: Build
        id: build
        run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --fast

