name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/**"
      - "katip-logstash/src/**"
      - "katip-logstash/package.yaml"
      - "logstash/src/**"
      - "logstash/package.yaml"
      - "monad-logger-logstash/src/**"
      - "monad-logger-logstash/package.yaml"
      - "stack*.yaml"
  pull_request:

jobs:
  dependencies:
    strategy:
      matrix:
        resolver:
          - "stack-lts-21"
          - "stack-lts-20"
          - "stack-lts-19"
          - "stack-lts-18"
          - "stack-lts-16.1"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4.1.0
        with:
          path: ${{ steps.install-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install dependencies
        run: stack --system-ghc --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --only-dependencies --fast

  build:
    needs:
      - dependencies

    strategy:
      matrix:
        resolver:
          - "stack-lts-21"
          - "stack-lts-20"
          - "stack-lts-19"
          - "stack-lts-18"
          - "stack-lts-16.1"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4.1.0
        with:
          path: ${{ steps.install-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build
        id: build
        run: stack --system-ghc --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --fast
